/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dev1;

import java.awt.CardLayout;

/**
 *
 * @author Benny
 */

public class Assignment extends javax.swing.JFrame {
private CardLayout mainCard;
private CardLayout mainParentCard;
private CardLayout employeeParentCard;
    /**
     * Creates new form Assignment
     */
    public Assignment() {
        initComponents();
        createMainCardLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCardLayoutPanel = new javax.swing.JPanel();
        Welkom_Label = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        EmployeeButton = new javax.swing.JButton();
        ProjectButton = new javax.swing.JButton();
        Parent = new javax.swing.JPanel();
        Employee_Screen = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        Employee_Go_To_Page_Button = new javax.swing.JButton();
        Employee_parent = new javax.swing.JPanel();
        Employee_Add_Screen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Project_screen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainCardLayoutPanel.setLayout(new java.awt.CardLayout());

        Welkom_Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Welkom_Label.setText("Welcome to Assignment 1");
        mainCardLayoutPanel.add(Welkom_Label, "card2");

        EmployeeButton.setText("Employee");
        EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeButtonActionPerformed(evt);
            }
        });

        ProjectButton.setText("Project");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(793, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(EmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(ProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainCardLayoutPanel.add(Menu, "card3");

        Parent.setLayout(new java.awt.CardLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Employee_Go_To_Page_Button.setText("Go to page");

        Employee_parent.setLayout(new java.awt.CardLayout());

        jLabel2.setText("YOU ARE ON EMPLOYEE ADDB SCREEN");

        javax.swing.GroupLayout Employee_Add_ScreenLayout = new javax.swing.GroupLayout(Employee_Add_Screen);
        Employee_Add_Screen.setLayout(Employee_Add_ScreenLayout);
        Employee_Add_ScreenLayout.setHorizontalGroup(
            Employee_Add_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_Add_ScreenLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        Employee_Add_ScreenLayout.setVerticalGroup(
            Employee_Add_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_Add_ScreenLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        Employee_parent.add(Employee_Add_Screen, "card2");

        javax.swing.GroupLayout Employee_ScreenLayout = new javax.swing.GroupLayout(Employee_Screen);
        Employee_Screen.setLayout(Employee_ScreenLayout);
        Employee_ScreenLayout.setHorizontalGroup(
            Employee_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_ScreenLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(Employee_Go_To_Page_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Employee_parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Employee_ScreenLayout.setVerticalGroup(
            Employee_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_ScreenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Employee_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_Go_To_Page_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(Employee_parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(Employee_Screen, "card2");

        javax.swing.GroupLayout Project_screenLayout = new javax.swing.GroupLayout(Project_screen);
        Project_screen.setLayout(Project_screenLayout);
        Project_screenLayout.setHorizontalGroup(
            Project_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        Project_screenLayout.setVerticalGroup(
            Project_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        Parent.add(Project_screen, "card3");

        mainCardLayoutPanel.add(Parent, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainCardLayoutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainCardLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeButtonActionPerformed
        goToEmployee_Screen();
    }//GEN-LAST:event_EmployeeButtonActionPerformed

    private void createMainCardLayout() {
   
        mainCardLayoutPanel.getLayout().addLayoutComponent("employee_screen", Employee_Screen);
        mainCardLayoutPanel.getLayout().addLayoutComponent("project_screen", Project_screen);
        mainCard = (CardLayout) mainCardLayoutPanel.getLayout();
    }
        private void goToEmployee_Screen() {
        mainCard.show(Parent, "employee_screen");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeButton;
    private javax.swing.JPanel Employee_Add_Screen;
    private javax.swing.JButton Employee_Go_To_Page_Button;
    private javax.swing.JPanel Employee_Screen;
    private javax.swing.JPanel Employee_parent;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Parent;
    private javax.swing.JButton ProjectButton;
    private javax.swing.JPanel Project_screen;
    private javax.swing.JLabel Welkom_Label;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainCardLayoutPanel;
    // End of variables declaration//GEN-END:variables
}
